lexik_jwt_authentication:
    secret_key:       '%kernel.project_dir%/config/jwt/private.pem' # Chemin de la clé privée
    public_key:       '%kernel.project_dir%/config/jwt/public.pem'  # Chemin de la clé publique
    pass_phrase:      'franck'                        # Passphrase utilisée lors de la génération de la clé privée
    token_ttl:        3600                                          # Durée de validité du token en secondes
